# IDs used to name folders
computer_id: B
experiment_id: 10

# Model and data-set name
# Valid model names are: deep_ar, deep_factor, deepstate, lstm, n_beats, mqcnn, mqrnn, rnn2qr, simple_feed_forward, wavenet
# Any GluonTS data-set name is valid, use "generate" to create random noise.
model: deep_ar
dataset: electricity

# Arguments passed to the GluonTS model. freq and prediction_length as null causes the dataset defaults to be used.
model_args:
  freq: null
  prediction_length: null

# Arguments passed to the GluonTS trainer
trainer_args:
  weight_seed: 0
  batch_seed: 0
  ctx: gpu
  epochs: 20
  learning_rate: 0.001

# Number of times to repeat every combination of parameters
num_repetitions: 100

# Decide wich seeds to increment: "weights", "batch" or "both" 
increment: weights

# Use validaiton data during training or not
use_val_data: True

# Track vaious metrics of the neural network with MXBoard (i.e. loss, gradients, etc.)
track_training: True

# Save weights after training
save_weights: True