# The ID used to tag files created during the experiment
experiment_id: 3

# Lists of parameters to use when running an experiment
models: [deep_ar]
datasets: [electricity]
epochs: [20]
learning_rates: [0.001]
context: gpu  # decide if running experiment on cpu or gpu

# Number of times to repeat every combination of parameters
num_repeats: 10

# The random seed. Null means not set
random_seed: 0
