# The ID used to tag files created during the experiment
experiment_id: 1

# Lists of parameters to use when running an experiment
models: [deep_factor]
datasets: [electricity]
epochs: [5]
learning_rates: [0.001]

# Number of times to repeat every combination of parameters
num_repeats: 1
