# IDs used to name folders
computer_id: B
experiment_id: 5

# Lists of parameters to use when running an experiment
models: [deep_ar]
datasets: [electricity]
epochs: [5]
learning_rates: [0.001]
context: cpu  # decide if running experiment on cpu or gpu

# Number of times to repeat every combination of parameters
num_repetitions: 2

# Sets the random seed. Use null to not set. Use "increment" when doing repetitions with different random seeds
random_seed: increment
