# IDs used to name folders
computer_id: B
experiment_id: 1

# Lists of parameters to use when running an experiment
models: [lstm]
datasets: [electricity]
epochs: [20]
learning_rates: [0.001]
context: gpu  # decide if running experiment on cpu or gpu

# Number of times to repeat every combination of parameters
num_repetitions: 100

# Sets the random seed. Use null to not set. Use "increment" when doing repetitions with different random seeds
random_seed: increment

# Track vaious metrics of the neural network in tensorboard (i.e. loss, gradients, etc.)
track_training: False
