# Model type
model_name: "deep_ar"

trainer: {"ctx": "gpu", "epochs": 1, "learning_rate": 0.001}

hyperparams: {"prediction_length": 10, "context_length": 10, "freq": H}

dataset_name: "generate"

dataset_path: null

cross_val: False
# we need to check if the folder exists
exp_num: 1