# Model type
model_name: "simple_feed_forward"

trainer: {"ctx": "cpu", "epochs": 1, "learning_rate": 0.001}

hyperparams: {"prediction_length": 100, "context_length": 100, "freq": "1B"}

dataset_name: "exchange_rate"

dataset_path: none